import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = { title: "About", description: "Learn who Quench Life is, what we believe, and who leads the church." };

export default function AboutPage() {
  return <main>
    <section className="page-hero"><div className="wrap"><p className="eyebrow">About Quench Life</p><h1>Jesus at the center of <span className="hl">everything.</span></h1><p className="lede" style={{ marginTop: "1.4rem" }}>Quench Life Christian Fellowship is a non-denominational church in Dublin, California. We gather around Scripture, prayer, worship, fellowship, discipleship, and service.</p></div></section>
    <section className="band"><div className="wrap split"><div><p className="eyebrow">Our mission</p><h2 style={{ marginTop: ".8rem", fontSize: "clamp(2rem,4.4vw,3rem)", fontWeight: 300 }}>Lead people to Jesus, grow them in faith, and equip them to serve.</h2><p className="lede" style={{ marginTop: "1.1rem" }}>Our vision is to see every member in every generation living a filled life in Jesus Christ.</p></div><blockquote className="quote">“Whoever drinks the water I give them will never thirst.”<cite>John 4:14</cite></blockquote></div></section>
    <section><div className="wrap"><div className="sec-head"><p className="eyebrow">What we believe</p><h2>A short statement of faith.</h2></div><div className="cards">{[["Jesus Christ", "Jesus Christ is Lord, fully God and fully human, who died and rose again for our salvation."], ["The Bible", "The Bible is God-breathed and provides the foundation for our teaching and life together."], ["The Church", "The church is a family of people who worship God, practice fellowship, make disciples, and serve their neighbors."], ["The Holy Spirit", "The Holy Spirit gives believers power to follow Jesus, understand Scripture, and serve others."]].map(([title, text]) => <article className="card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="band"><div className="wrap"><div className="sec-head"><p className="eyebrow">Leadership</p><h2>Meet the people serving Quench Life.</h2></div><div className="faces"><article className="face"><Image src="/quenchlife/img/face-pastor.jpg" alt="Pastor Robert Scott" width={112} height={112} /><h3>Robert L. Scott Jr.</h3><p>Lead Pastor</p><p>Robert teaches Scripture and leads Quench Life with his wife, Carolyn.</p></article><article className="face"><Image src="/quenchlife/img/face-greeter.jpg" alt="Carolyn Scott" width={112} height={112} /><h3>Carolyn Scott</h3><p>Executive Director</p><p>Carolyn supports church administration, leadership, and children&apos;s ministry.</p></article><article className="face"><Image src="/quenchlife/img/face-kids-lead.jpg" alt="Quench Life kids ministry leader" width={112} height={112} /><h3>Kids Ministry Team</h3><p>Children&apos;s Ministry</p><p>Our team welcomes children and helps families get settled on Sunday mornings.</p></article></div></div></section>
  </main>;
}
