import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Your First Sunday", description: "Everything you need before visiting Quench Life in Dublin, California." };

export default function VisitPage() {
  return (
    <main>
      <section className="page-hero"><div className="wrap"><p className="eyebrow">Planning your first visit</p><h1>You won&apos;t feel like an <span className="hl">outsider.</span></h1><p className="lede" style={{ marginTop: "1.4rem" }}>Walking into a church you&apos;ve never been to is genuinely uncomfortable. So here&apos;s everything you need before you have to ask a single person.</p><dl className="essentials"><div className="essential"><dt>When</dt><dd>Sundays, 11:00 AM<span>Doors open at 10:30</span></dd></div><div className="essential"><dt>Where</dt><dd>7080 Donlon Way<span>Suite 217, Dublin CA</span></dd></div><div className="essential"><dt>How long</dt><dd>About 75 minutes<span>Coffee before and after</span></dd></div><div className="essential"><dt>What to wear</dt><dd>Whatever you own<span>Jeans are the norm</span></dd></div></dl><div className="cta-row"><a className="btn btn-solid" href="https://maps.google.com/?q=7080+Donlon+Way+Suite+217+Dublin+CA+94568">Open in Maps</a><Link className="btn btn-ghost" href="/listen">Watch a service first</Link></div></div></section>
      <section className="band"><div className="wrap split"><div><p className="eyebrow">Getting here</p><h2 style={{ marginTop: ".8rem", fontSize: "clamp(2rem,4.4vw,3rem)", fontWeight: 300 }}>Finding the door is the hardest part. Let&apos;s fix that.</h2><ul className="arrive"><li><span className="icon">⌖</span><div><h3>Parking</h3><p>Free parking is available near the building, with street parking along Donlon Way.</p></div></li><li><span className="icon">↗</span><div><h3>Which door</h3><p>Use the main entrance, then head to the second floor and Suite 217. Look for the Quench Life sign.</p></div></li><li><span className="icon">◷</span><div><h3>When to show up</h3><p>Ten minutes early is perfect, enough time for coffee and a seat. Running late is fine too.</p></div></li><li><span className="icon">♿</span><div><h3>Accessibility</h3><p>Call ahead if you need help getting comfortable and we&apos;ll sort it out with you.</p></div></li></ul></div><div className="map"><Image src="/quenchlife/img/map-static.jpg" alt="Map showing Quench Life at 7080 Donlon Way, Dublin CA" fill sizes="(max-width: 900px) 90vw, 500px" /></div></div></section>
      <section><div className="wrap split"><div><p className="eyebrow">Minute by minute</p><h2 style={{ marginTop: ".8rem", fontSize: "clamp(2rem,4.4vw,3rem)", fontWeight: 300 }}>The whole morning, start to finish.</h2><p className="lede" style={{ marginTop: "1.1rem" }}>Nobody will call you out or make you stand up and say your name. You can sit in the back and just watch.</p><figure className="photo arch" style={{ marginTop: "2.4rem", aspectRatio: "5/4" }}><Image src="/quenchlife/img/room-filling-up.jpg" alt="The meeting room filling up before Sunday service" fill sizes="(max-width: 900px) 90vw, 500px" /></figure></div><div className="timeline">{[["10:30 – 10:55 AM", "Coffee and hellos"], ["11:00 AM", "We start on time-ish"], ["11:25 AM", "The teaching"], ["12:05 PM", "Prayer, and the offering"], ["12:15 PM onward", "Nobody hurries off"]].map(([time, title]) => <div className="tl" key={title}><span className="clock">{time}</span><h3>{title}</h3><p>Come as you are. There is room to listen quietly, ask questions, and stay as long as you like or slip out. No pressure.</p></div>)}</div></div></section>
      <section className="band"><div className="wrap"><div className="sec-head"><p className="eyebrow">Coming with kids</p><h2>Bring them. Wiggles included.</h2><p className="lede">Kids are welcome in the service. Families can sit together, use the space at the back, or step out when needed.</p></div></div></section>
      <section><div className="narrow"><div className="sec-head"><p className="eyebrow">Still wondering something</p><h2>Ask a real person. We&apos;d rather you did.</h2></div><div className="contact"><a className="tile" href="tel:9255494054"><span>Call or text</span><strong>925-549-4054</strong></a><a className="tile" href="mailto:info@quenchlife.org"><span>Email</span><strong>info@quenchlife.org</strong></a></div></div></section>
    </main>
  );
}
